/**
 * The app's actual Privacy policy / Terms of service copy — one source of
 * truth shared by Settings' "Privacy policy"/"Terms of service" rows and
 * the login page's "By continuing, you agree to..." footer, so the two
 * surfaces can never drift out of sync with each other.
 */

export interface LegalDoc {
  title: string;
  body: string;
}

export const PRIVACY_POLICY: LegalDoc = {
  title: 'Privacy policy',
  body: 'EduM8 stores the documents you upload and the conversations you start so it can answer questions grounded in your material. Your documents are chunked and indexed for retrieval only — they are never used to train models and are never shared with other users. You can export a copy of your data or delete it entirely from the Settings screen at any time.',
};

export const TERMS_OF_SERVICE: LegalDoc = {
  title: 'Terms of service',
  body: 'EduM8 is provided as-is as a research reading assistant. Answers are generated by a language model grounded in the documents you upload — they can be incomplete or wrong, so always verify important claims against the cited sources before relying on them.',
};
