"""Milestone 5.1 Part 12/15/22 — the compiler service's own request/
response contract. Deliberately narrow: exactly two input fields (never
an arbitrary file tree — Part 12), and a response shape that never
leaks container paths, environment variables, or raw stack traces
(Part 15) — see app/log_sanitizer.py for how the raw TeX log is cleaned
before it ever reaches this schema."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

CompileStatus = Literal["success", "error", "timeout"]


class CompileRequest(BaseModel):
    """`job_id` is generated by the calling backend purely for log
    correlation across the two services — never trusted as an identity
    or ownership claim (this service has no concept of users/projects at
    all, matching evidence-service's own statelessness).

    Milestone 5.3 Part 17 — `extra_files` extends the original two-file
    contract to a bounded, explicit set of additional project files: the
    calling backend has ALREADY resolved these from a Writing Project's
    file tree (never client-supplied paths — see rag-backend's
    app/core/writing_file_validation.py) and base64-encodes every value
    here regardless of whether the underlying file is text or binary, so
    this schema doesn't need to know or care which. Keys are relative
    paths like "sections/introduction.tex" or "figures/framework.png" —
    still independently re-validated against traversal by THIS service
    too (app/compiler.py's `_safe_relative_path`), never trusted just
    because the caller is our own backend (Part 45: defense in depth)."""

    job_id: str = Field(min_length=1, max_length=64)
    main_tex: str
    references_bib: str
    extra_files: dict[str, str] = Field(default_factory=dict)


class Diagnostic(BaseModel):
    severity: Literal["error", "warning"]
    message: str
    line: int | None = None


class CompileResponse(BaseModel):
    status: CompileStatus
    diagnostics: list[Diagnostic] = Field(default_factory=list)
    # Sanitized, truncated raw log — see app/log_sanitizer.py. Never the
    # unmodified subprocess output (which could contain absolute
    # container paths — Part 15/23).
    log_excerpt: str = ""
    duration_ms: float = 0.0
    pdf_base64: str | None = None
    pdf_size_bytes: int | None = None
    page_count: int | None = None


class ErrorResponse(BaseModel):
    error: str
    detail: str


class HealthResponse(BaseModel):
    status: Literal["ready"]
    pdflatex_version: str | None = None
