"""Milestone 5.5 Part 22 — repository for CompileArtifact. Same "plain
dataclass read-shape, Session-based, ownership-checked-by-user_id-filter"
convention as every other repository in this codebase.

`sweep_expired()` is called at the top of both the compile POST and PDF
GET routes (routes_writing.py) — deliberately a plain query-and-delete on
every request rather than a scheduled background job, matching
WritingImportSessionsRepository.sweep_expired's own identical reasoning
(and, one level further back, compile_artifact_cache.py's original
in-process TTL-pruning-on-every-call design — this preserves that same
"no extra infra" posture, just made visible across workers)."""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from app.core.time_utils import ensure_utc
from app.db.models_writing import CompileArtifact


@dataclass(frozen=True)
class CompileArtifactRecord:
    id: uuid.UUID
    user_id: uuid.UUID
    project_id: uuid.UUID
    storage_key: str
    created_at: datetime
    expires_at: datetime


def _to_record(row: CompileArtifact) -> CompileArtifactRecord:
    return CompileArtifactRecord(
        id=row.id,
        user_id=row.user_id,
        project_id=row.project_id,
        storage_key=row.storage_key,
        created_at=row.created_at,
        expires_at=row.expires_at,
    )


class CompileArtifactsRepository:
    def __init__(self, db: Session) -> None:
        self._db = db

    def sweep_expired(self) -> list[str]:
        """Deletes every artifact (any user) past its TTL and returns
        their storage_keys so the caller can delete the staged PDF bytes
        too (this repository never touches the filesystem itself, same
        separation-of-concerns as every other repository here)."""
        now = datetime.now(UTC)
        rows = list(
            self._db.execute(select(CompileArtifact).where(CompileArtifact.expires_at < now))
            .scalars()
            .all()
        )
        keys = [r.storage_key for r in rows]
        if rows:
            # synchronize_session=False — see
            # WritingImportSessionsRepository.sweep_expired's identical
            # comment for why this is safe here (naive-vs-aware `now`
            # comparison quirk on SQLite; `keys` is already captured).
            self._db.execute(
                delete(CompileArtifact).where(CompileArtifact.expires_at < now),
                execution_options={"synchronize_session": False},
            )
            self._db.commit()
        return keys

    def create(
        self,
        *,
        compile_id: uuid.UUID,
        user_id: uuid.UUID,
        project_id: uuid.UUID,
        storage_key: str,
        ttl_seconds: float,
    ) -> CompileArtifactRecord:
        """`compile_id` is generated by the CALLER (routes_writing.py)
        rather than here, so it can mint the storage key under the exact
        same id the DB row ends up with — mirrors
        WritingImportSessionsRepository.create's identical reasoning."""
        now = datetime.now(UTC)
        row = CompileArtifact(
            id=compile_id,
            user_id=user_id,
            project_id=project_id,
            storage_key=storage_key,
            expires_at=now + timedelta(seconds=ttl_seconds),
        )
        self._db.add(row)
        self._db.commit()
        self._db.refresh(row)
        return _to_record(row)

    def get(
        self, *, user_id: uuid.UUID, project_id: uuid.UUID, compile_id: uuid.UUID
    ) -> CompileArtifactRecord | None:
        """Returns None for a missing, expired, OR ownership-mismatched
        entry — the caller (route) maps every one of those identically to
        404, never distinguishing "wrong owner" from "doesn't exist"
        (Part 42), exactly matching compile_artifact_cache.
        CompileArtifactCache.get's own documented contract."""
        row = self._db.get(CompileArtifact, compile_id)
        if row is None or row.user_id != user_id or row.project_id != project_id:
            return None
        if ensure_utc(row.expires_at) < datetime.now(UTC):
            return None
        return _to_record(row)
