"""Milestone 5.4 (LaTeX Templates & Project Import) Part 9/31/32 —
repository for WritingImportSession. Same "plain dataclass read-shape,
Session-based, ownership-checked-by-user_id-filter" convention as every
other repository in this codebase.

`sweep_expired()` is called at the top of both the inspect and confirm
routes (Part 32: "no unbounded accumulation") — deliberately a plain
query-and-delete on every request rather than a scheduled background
job, matching this codebase's existing "no extra infra" posture (see
app/core/compile_artifact_cache.py's own identical reasoning for staying
in-process rather than adding a task scheduler for a single milestone's
worth of cleanup need)."""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

from sqlalchemy import delete, select
from sqlalchemy.orm import Session

from app.core.time_utils import ensure_utc
from app.core.writing_project_import import ImportInspection
from app.db.models_writing import WritingImportSession


@dataclass(frozen=True)
class WritingImportSessionRecord:
    id: uuid.UUID
    user_id: uuid.UUID
    original_filename: str
    storage_key: str
    inspection: ImportInspection
    created_at: datetime
    expires_at: datetime


def _to_record(row: WritingImportSession) -> WritingImportSessionRecord:
    return WritingImportSessionRecord(
        id=row.id,
        user_id=row.user_id,
        original_filename=row.original_filename,
        storage_key=row.storage_key,
        inspection=ImportInspection.from_json_dict(json.loads(row.inspection_json)),
        created_at=row.created_at,
        expires_at=row.expires_at,
    )


class WritingImportSessionsRepository:
    def __init__(self, db: Session) -> None:
        self._db = db

    def sweep_expired(self) -> list[str]:
        """Deletes every session (any user) past its TTL and returns
        their storage_keys so the caller can delete the staged ZIP bytes
        too (this repository never touches the filesystem itself, same
        separation-of-concerns as every other repository here)."""
        now = datetime.now(timezone.utc)
        rows = list(
            self._db.execute(select(WritingImportSession).where(WritingImportSession.expires_at < now))
            .scalars()
            .all()
        )
        keys = [r.storage_key for r in rows]
        if rows:
            # synchronize_session=False: the SELECT above already loaded
            # `rows` into this Session's identity map with whatever
            # `expires_at` the DB round-trip gave back — tz-NAIVE on
            # SQLite (see ensure_utc's own docstring), tz-aware on
            # Postgres. The ORM's default "evaluate" sync strategy would
            # re-check this same WHERE clause in pure Python against
            # those already-loaded objects to decide what to expire,
            # comparing a naive `expires_at` against the aware `now`
            # below and crashing on SQLite. Skipping session-sync here is
            # safe: `keys` was already captured above, and every one of
            # these rows is only ever fetched again by id-and-owner (see
            # `get()`), never re-listed from a stale in-memory collection.
            self._db.execute(
                delete(WritingImportSession).where(WritingImportSession.expires_at < now),
                execution_options={"synchronize_session": False},
            )
            self._db.commit()
        return keys

    def create(
        self,
        *,
        session_id: uuid.UUID,
        user_id: uuid.UUID,
        original_filename: str,
        storage_key: str,
        inspection: ImportInspection,
        ttl_minutes: int,
    ) -> WritingImportSessionRecord:
        """`session_id` is generated by the CALLER (routes_writing_import.py)
        rather than here, so it can mint the storage key under the exact
        same id the DB row ends up with — the two are the same value by
        construction, never independently generated and then hoped to
        stay in sync."""
        now = datetime.now(timezone.utc)
        row = WritingImportSession(
            id=session_id,
            user_id=user_id,
            original_filename=original_filename,
            storage_key=storage_key,
            inspection_json=json.dumps(inspection.to_json_dict()),
            expires_at=now.replace(microsecond=0) + timedelta(minutes=ttl_minutes),
        )
        self._db.add(row)
        self._db.commit()
        self._db.refresh(row)
        return _to_record(row)

    def get(self, user_id: uuid.UUID, session_id: uuid.UUID) -> WritingImportSessionRecord | None:
        row = self._db.get(WritingImportSession, session_id)
        if row is None or row.user_id != user_id:
            return None
        if ensure_utc(row.expires_at) < datetime.now(timezone.utc):
            return None
        return _to_record(row)

    def delete(self, user_id: uuid.UUID, session_id: uuid.UUID) -> str | None:
        """Returns the deleted row's storage_key (for the caller to
        clean up staged bytes) or None if no matching row existed for
        this user — indistinguishable from "already gone", matching
        this codebase's ownership-check convention elsewhere."""
        row = self._db.get(WritingImportSession, session_id)
        if row is None or row.user_id != user_id:
            return None
        storage_key = row.storage_key
        self._db.delete(row)
        self._db.commit()
        return storage_key
